- package:
  - name: cardano-wallet-core
  - section:
    - name: test:unit
    - message:
      - name: Weeds exported
      - module:
        - name: Cardano.Wallet.DB.StateMachine
        - identifier: showLabelledExamples
  - section:
    - name: test:unit bench:db
    - message:
      - name: Module reused between components
- package:
  - name: cardano-wallet-launcher
  - section:
    - name: library
    - message:
      - name: Module not compiled
      - module: Cardano.Launcher.Windows
- package:
  - name: cardano-wallet-jormungandr
  - section: test:integration
